# Site settings
title: Anargya Website
description: "Build with Jekyll."
url: "https://anargya-anubhawa.github.io/"
author:
  name: "Anargya Anubhawa"
  email: "anargya.anubhawa@gmail.com"
  url: "https://anargya-anubhawa.github.io/"

# Build settings
baseurl: /post/ #Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

# Plugins
gems: 
    - jekyll-sitemap
    - jekyll-paginate

plugins:
    - jekyll-sitemap
    - jekyll-paginate