# Site settings
title: Anargya Website
description: "Build with Jekyll."
url: "https://anargya-anubhawa.github.io/"
author:
  name: "Anargya Anubhawa"
  email: "anargya.anubhawa@gmail.com"
  url: "https://anargya-anubhawa.github.io/"

# Build settings
baseurl: / #Change this to your relative path (ex: /blog/), or leave just a /.
markdown: kramdown
source: .
destination: ./_site
paginate: 5
paginate_path: /page:num/
permalink: /:title/
timezone: Asia/Jakarta
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "2.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

jekyll-archives:
  enabled: [true]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Plugins
gems: 
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-archives
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-archives
